### ISSUE TITLE
Dropshadow clipping

### ISSUE THREAD

**Issue by akoskinen** [nickstamas/Sketch-Better-Android-Export#2]
Great plugin, thanks!.
Is the issue of dropshadow clipping something that can be fixed?

**Comment by pellens** [comment]
Same issue, works great but need the shadows :)

**Comment by nickstamas** [comment]
I've updated the plugin to support slices. If you need to include a dropshadow, you can create a slice that includes the shadow. Slice exports include everything within their frame.
