### ISSUE TITLE
iOS?

### ISSUE THREAD

**Issue by emexmedovic** [nickstamas/Sketch-Better-Android-Export#4]
Is addition of iOS export an option?

Even though it's simple enough to export for iOS, it would be even easier with the plug-in, because:

1) you wouldn't have to set-up (or worry about forgetting to set-up) @1x, @2x and @3x, 
2) you wouldn't need to convert to slice in cases when your icon has some invisible padding which you want exported (your plug-in exports the transparent area as well, which I tested and liked a lot).

**Comment by designedbyDC** [comment]
@nickstamas - :) Seems like next few days never happened. I did manage to fork your code to make it work for iOS (note: the code is not as elegant as yours, but it does work.)

https://github.com/designedbyDC/Asset-Export-for-iOS-and-Android
