### ISSUE TITLE
xlarge folder support?

### ISSUE THREAD

**Issue by nillabeanrc88** [nickstamas/Sketch-Better-Android-Export#6]
Sometimes I have to export assets to xlarge folders:

drawable-xlarge-xhdpi
drawable-xlarge-xxhdpi
drawable-xlarge-xxxhdpi

right now thats not supported. would this happen in the future?

**Comment by nickstamas** [comment]
Can you explain a little more in detail about what you're looking to do?

**Comment by nillabeanrc88** [comment]
Hey Nick, 


I was actually able to modify the original jstalk file. I really just needed the ability to export to Xlarge dpi folders. I attached in the email. 


   
Richard Bean 
UI / UX Designer
301•399•6880 <tel:>richardcbean@gmail.com <mailto:richardcbean@gmail.com>
Chicago, IL
