### ISSUE TITLE
Blank resulting files when exporting from slice

### ISSUE THREAD

**Issue by PGRdesign** [nickstamas/Sketch-Better-Android-Export#7]
Hi nickstamas,

I've been using your plugin since it's one of the most usefuls since I'm working always on 1x scale, and most of them are based on 2x+ designs.

Everything worked fine so far but today I needed to export an asset which sketch by default wasn't mapping well since it had a shadow and by default they won't be within the slice area by default, so what I did is what I usually do in those cases, add a slice overlay and make it my desired size.

Once done I choose "export group contents only" this way it exports what's inside of the folder but preserves transparency on background.

Well, with your plugin the resulting file is always a blank file, while exporting with the default sketch option gives you the proper result.

Doesn't this plugin support slices?

Thanks!

**Comment by nickstamas** [comment]
It's been a while since I've looked at the code, but I can take a look.

**Comment by nickstamas** [comment]
@PGRdesign Should be fixed now if you download the latest.

**Comment by PGRdesign** [comment]
Great man! thanks a lot for your quick response :+1:
