### ISSUE TITLE
plugin doesn't work after Sketch 3.4 upgrade

### ISSUE THREAD

**Issue by antynomia** [nickstamas/Sketch-Better-Android-Export#9]
Setup:
https://www.dropbox.com/s/jg1lhqqdhzjmxuc/Zrzut%20ekranu%202015-10-26%2018.36.48.png?raw=1

After using plugin all layers are hidden, exporting doesn't export acutally (showing gray rectangle):
https://www.dropbox.com/s/fnsp14kc30ea125/Zrzut%20ekranu%202015-10-26%2018.37.04.png?raw=1

**Comment by nickstamas** [comment]
@antynomia Thanks for the heads up, I'll try to take a look soon.

**Comment by PGRdesign** [comment]
Same issue here. It would be nice if that could be solved. I love the simplicity and effectiveness of this plugin :grinning:

**Comment by nickstamas** [comment]
Should be fixed now guys thanks to someone's pull request!
